### ISSUE TITLE
Grep speed 

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#102]
I have a text file (a log) sized 110 MiB with 530k lines. I do Ungrep with an expression that eliminates around 510k lines. In the latest build this takes up 27 seconds. In one of the oldest builds (2015) where Ungrep was first implemented this takes up 15 seconds.

Question: you were supposed to optimize grep/ungrep (and you have added a progressbar to the statusbar) - why ungrep became almost twice as **slow** as it used to be?

**Comment by cshnik** [comment]
It looks like specified delay relates to progress indicator updates (provides smooth and pretty look). Please check [this build](https://github.com/ProgerXP/Notepad2e/blob/028edaed02349cd5029f3886988cc7ebf872a522/bin/Win32/Release/Notepad2e.exe?raw=true) and confirm it provides appropriate Grep's performance.

**Comment by cshnik** [comment]
Are there any news on the test build's performance? Please confirm if we need to improve progress indicator updates to increase Grep performance.

**Comment by ProgerXP** [comment]
Speed demonstrated by the current build (https://github.com/ProgerXP/Notepad2e/commit/efb59ecef709d22766ffcd20e3cf59e8c9df81c2) is acceptable. Fix the code and this issue is resolved.

**Comment by ProgerXP** [comment]
Another related issue. Why Grep/Ungrep with regexp is drastically slower than Find or Replace?

For example, take a file with 150k lines. You can generate one e.g. with Linux:
```
seq -f 'head %1.2f tail' 0.0 0.01 10000.0 | shuf >random.txt
```
(this will produce 1m lines)

Now open it in Notepad 2e. Try doing the following:
1. Find `2.... t` (i.e. find lines with `2`, followed by 4 symbols, space and `t`) - instant.
2. Replace `head 2` with empty string - instant.
3. Replace `2.... t` with empty string - almost instant.
4. Grep `head 2` (in non-regexp mode) - ~5 seconds.
5. Grep `2.... t` (regexp mode) - hangs forever.

I would understand if Grep in regexp mode would take, like, 10 or 20 times longer - by analogy with Replace which takes slightly longer time in regexp mode than in plain text mode. If you take 2015 build of Notepad 2e (from master) you will see that regexp Grep takes ~25 seconds. 

Why dev regexp is so slow?

**Comment by cshnik** [comment]
I tested your cases and was unable to reproduce specified hang with current dev-build of Notepad2e.
However, I made an additional review for the Grep-subroutine and improved the code to call Scintilla's-functionality directly bypassing Windows messaging mechanism. I made new test build and compared performances for [Notepad2e_master](https://github.com/ProgerXP/Notepad2e/commit/396dda1de9744f47c1b46259fc104c1c990c1130#diff-6f4035985bf2aedb083152033f338c1c), [Notepad2e_before_optimization](https://github.com/ProgerXP/Notepad2e/blob/efb59ecef709d22766ffcd20e3cf59e8c9df81c2/bin/Win32/Release/Notepad2e.exe) and [Notepad2e_after_optimization](https://github.com/ProgerXP/Notepad2e/commit/b637a713af32d6df50b4f08a5d3f73fca6346b02) on the test file with 1M lines. Here is my final chart with your test cases from above:

| Build \Test | 1 | 2 | 3 | 4 | 5 |
| --- | --- | --- | --- | --- | --- |
| Notepad2e_master | 0 sec | 1 sec | 1 sec | 121 sec | 122 sec |
| Notepad2e_before_optimization | 0 sec | 1 sec | 1 sec | 15 sec | 15 sec |
| Notepad2e_after_optimization | 0 sec | 1 sec | 1 sec | 15 sec | 15 sec |   

Thus, Grep's implementation in the dev branch works in ~8 times faster than Grep from master branch when testing cases 4 and 5.
Unfortunately, my local tests showed no performance increase but I assume it may depend on the total OS load when working with Notepad2e (I used my completely free desktop).

Regarding the difference between Grep and Replace: Grep is a more complex operation because it requires additional actions to perform (comparing to Replace), e.g: "Retrieve end-of-line", "Remove line" (which causes updating of Scintilla's storage (line count, indexes, memory blocks, etc)). While simple replace of substring within a single line will never cause rebuilding of the global document's structure. That's why Grep and Replace can't be directly compared.

**Comment by ProgerXP** [comment]
I was able to localize the issue. I have discovered that using build from `03/05/2017 2:58:22.15` results in a hang I have described while a build from the following day (`04/11/2017 1:04:52.91`) doesn't hang.

I don't see any speed difference between 04/11 version and your last version so let's revert it because it's messing with Scintilla internals. But please check what was the problem between those two builds that has caused the hang.

**Comment by cshnik** [comment]
> I was able to localize the issue. I have discovered that using build from 03/05/2017 2:58:22.15 results in a hang I have described while a build from the following day (04/11/2017 1:04:52.91) doesn't hang.

This was not a hang but a slow/ineffective work of the first implementation of BoostRegEx.
The issue was fixed with the changes related to #90 .

> I don't see any speed difference between 04/11 version and your last version so let's revert it because it's messing with Scintilla internals.

Latest changes related to using of the officially documented way to improve performance when working with Scintilla control: http://www.scintilla.org/Steps.html, "The fast way to control Scintilla"-section. To my mind, we should always use this approach, because there are 2 important advantages (vs SendMessage-calls):
1. Fast work: there will be no data transfer to/from Scintilla using Windows messages, direct calls(which are always fast) are used instead.
2. Good code: using of predefined SciCall_()-macroses will improve the code readability, reduce the number of text/chance for a typo and increase the development speed.

Please confirm if you still insist on a rollback for this commit.

**Comment by ProgerXP** [comment]
> Please confirm if you still insist on a rollback for this commit.

I see your point, then it's not necessary. It seems the page you have linked to is outdated though - there's no need to obtain the functions' pointers, right (you are simply using Scintilla_DirectFunction)?

**Comment by ProgerXP** [comment]
I am still not happy with Un/Grep's speed. Take my sample file from above: https://github.com/ProgerXP/Notepad2e/issues/102#issuecomment-294141472

If you run GNU `grep`, it will be done in 24 ms. If you use Notepad 2e's Grep, it will take 19 seconds - 791 times as long.

```
$ time grep 123 random.txt
real    0m0.024s
```

This is really not acceptable. I think the performance is poor due to constant refresh & update of the text window. However, it's useless updating it because it's not usable anyway (if you edit the contents the result you get after Grep is finished is corrupted). In this case, we should do the entire operation in memory.

This equally applies to other progress bar-enabled commands like Base64 - the window should be updated only once after the operation is complete.

**Comment by ProgerXP** [comment]
Seriously, I currently have to frequently filter files that are 10k-100k lines and Grep/Ungrep is absurdly slow. It has to be rewritten from scratch for sure, possibly with Base64 and other encoding commands. 

Take a look at this before other tasks.

**Comment by cshnik** [comment]
The main expected reason of the performance loss for find&replace/grep/ungrep commands is that Notepad2 was originally developed as Scintilla-based text editor which means it states the way it operates with data: Scintilla's engine represents the interface to access/modify the data. Due to the fact Notepad2e works (as original Notepad2 does) in terms of high level Scintilla's commands ("find text", "set selection to interval", "replace selection") and understanding of the initial requirements for Scintilla engine (represent UI, provide high level/fast/convenient interfaces) and cost for these (performance loss for internal structures/updates) it was never expected to make Notepad2 be directly compared with console app like grep.

Please provide exact commands/data to compare `Notepad2` vs `Notepad2e` vs `grep` performances to be sure I can reproduce exactly the same issue.

**Comment by ProgerXP** [comment]
> it was never expected to make Notepad2 be directly compared with console apps like grep.

It does not explain at all why Grep/Ungrep are slower than Notepad2's own facilities like Remove Blank Lines.

> Please provide exact commands/data 

Take jQuery.js: https://code.jquery.com/jquery-3.4.1.js

1. GNU `grep`:
`time grep -Fv // jquery-3.4.1.js`
0.046s

2. Notepad 2e Ungrep in non-regexp mode, string = `//`
14-15s

3. Notepad 2e Replace from `.*//.*` to (blank), followed by Remove Blank Lines (Alt+R):
2-3s

**Comment by cshnik** [comment]
Reduced the number of "process pending messages"-calls when inline progress bar (within status bar) is active. Please try new build.

**Comment by ProgerXP** [comment]
If we do not process any messages at all, how much faster it is than the old version and new version on your system given my previously described jQuery test?

**Comment by cshnik** [comment]
It takes now <2 seconds to complete Grep/Ungrep vs ~15 seconds before.

**Comment by ProgerXP** [comment]
With processing messages or not? If we do not process any messages at all, is it faster?

**Comment by cshnik** [comment]
No processing for pending messages is actually performed now. I'll make a code cleanup (remove unused code).

**Comment by ProgerXP** [comment]
Now it's much more usable. I don't see any difference in speed between Ungrep and Remove Blank Lines.
