### ISSUE TITLE
Autoclose XML corrupts UTF-8

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#112]
(This bug is present in the original Notepad2.)

Set document's encoding to UTF-8. Enable Settings > Auto Close HTML. Type `<ф>`. As you type `>`, you will see that instead of adding `</ф>` the program adds a corrupted `</XXX>` sequence.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
You didn't fix this. Observe the behaviour for <tag attrs> in ANSI and your fixed UTF-8 modes.

**Comment by cshnik** [comment]
Originally stated problem related to UTF-8 text encoding feature. Fixed implementation process non-ASCII characters properly when executing "Auto Close HTML"-feature in UTF-8 mode.
Please provide steps to reproduce if the problem remains.

**Comment by ProgerXP** [comment]
Don't blindly "fix" the problem please, put some thought into what you are doing.

Old code:
```
                  while (StrChrA(":_-.", *pCur) || IsCharAlphaNumericA(*pCur))
```

New code:
```
                  while (!bIsUTF8 && (StrChrA(":_-.", *pCur) || IsCharAlphaNumericA(*pCur))
                         || (bIsUTF8 && (pCur && *pCur != '>')))
```

Isn't it obvious that `*pCur != '>'` is very different from the original `StrChrA(":_-.", *pCur) || IsCharAlphaNumericA(*pCur)`?

**Comment by cshnik** [comment]
Done. Unicode-aware solution was implemented.

**Comment by ProgerXP** [comment]
Stop pushing code without testing it!

Test Latin and Russian tags in SBCS and MBCS while Autoclose is enabled.

**Comment by cshnik** [comment]
Unfortunately, I see no problems with using of latin/russian charaters when testing the feature with ANSI/Unicode/UTF-8/Cyrillic encodings.
Please provide your failed tests to increase the speed of bug fixing.

**Comment by ProgerXP** [comment]
1. Enable Autoclosing
2. Set document encoding to ANSI (1251)
3. Type `<я>`
4. The tag is not closed

**Comment by cshnik** [comment]
Fixed.
