### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#267]
These tests have been failing since at least 31 January:

1. CStringToBase64.TestBase64_StringSamples
1. CStringToHex.TestHex_FileSamples
1. CStringToHex.TestHex_StringSamples

**Comment by cshnik** [comment]
The following tests were fixed during #253:

- TestBase64_StringSamples
- TestHex_StringSamples

**Comment by ProgerXP** [comment]
These two now pass. CStringToHex.TestHex_FileSamples is still failing.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
1. DoRecodingTest is still failing and I have compared the files on the server - they are identical so the issue is not with different line breaks.
2. These 2 groups (src/Hex) of 3 files are identical which means there is an error in test data;

```
TestFile1_*_1250.txt
TestFile1_*_1251.txt
TestFile1_*_UTF8.txt
```

**Comment by cshnik** [comment]
Fixed.
