### ISSUE TITLE
Ctrl+Backtick edits all occurrences

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#302]
Document:

```
aa|
aa aa
```

Press Ctrl+Backtick: all 3 `aa` will be editing instead of none. 

This doesn't occur if cursor is on the second line.

**Comment by cshnik** [comment]
Fixed in the latest [change](https://github.com/ProgerXP/Notepad2e/commit/f4c66fea43415cb4b5a480c2abf6ebe7db60d0b4) for #286.

**Comment by ProgerXP** [comment]
This is still not correct - editing should not even start in this case. I have checked the previous versions and indeed it used to work like now, however, there is a discrepancy between Ctrl+Backtick and Ctrl+Tab: the latter does not start editing if there is only a single region to-be edited. Ctrl+Backtick should work the same way.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
```
aa|
aa
```

Ctrl+Backtick starts editing `aa` even though there's only 1 match on line.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
> This is still not correct - editing should not even start in this case. I have checked the previous versions and indeed it used to work like now, however, there is a discrepancy between Ctrl+Backtick and **Ctrl+Tab: the latter does not start editing if there is only a single region to-be edited. Ctrl+Backtick should work the same way**.

Why this regression is keeping to occur again and again? Please check the logic to ensure it's correct to avoid another bug-after-fix. If needed, clarify it with refactoring.

When user tries to enter Edit Mode via any means (Ctrl+Tab, Ctrl+backtick, etc.) and if there is only one edit region (e.g. document occurrence) then nothing should happen (keystroke should be ignored).

Currently, if you insert `aaa` into a large document in such places that only one occurrence is seen, and disable Document-Wise Edit Word then Ctrl+Tab on `aaa` would still enter Edit Mode, saying "Editing 1 occurrence".

That being said, there is no need for `occurrence%s` because of the reason above (https://github.com/ProgerXP/Notepad2e/issues/286#issuecomment-617418587).

**Comment by ProgerXP** [comment]
> Seems to have been fixed meanwhile.

No way, it's appearing again in 360e461: Ctrl+Tab happily enters edit mode on a document with `aa` on the first line and on the last line (beyond scrolling), saying `Editing 1 occurrence (visible only)`.

**Comment by cshnik** [comment]
Fixed.
